# Generated by Django 3.2 on 2021-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAPI', '0003_auto_20210420_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
