# Generated by Django 3.2 on 2021-04-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAPI', '0005_auto_20210420_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='registrationNo',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
