# Generated by Django 3.2 on 2021-04-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAPI', '0006_alter_business_registrationno'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='registrationNo',
            field=models.IntegerField(unique=True),
        ),
    ]
