# Generated by Django 3.2 on 2021-04-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageAPI', '0009_alter_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='manageAPI.user'),
            preserve_default=False,
        ),
    ]
