# Generated by Django 3.2 on 2021-04-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageAPI', '0011_alter_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manageAPI.user'),
            preserve_default=False,
        ),
    ]
